# Generated by Django 5.2.13 on 2026-06-19 19:19

from django.db import migrations, models


def migrate_existing_contacts(apps, schema_editor):
    RequisicaoLente = apps.get_model("lentes", "RequisicaoLente")
    ControleLente = apps.get_model("lentes", "ControleLente")
    User = apps.get_model("auth", "User")

    users_by_id = {
        user.id: getattr(user, "username", "")
        for user in User.objects.filter(
            id__in=RequisicaoLente.objects.exclude(usuario_contatou_id=None).values_list(
                "usuario_contatou_id",
                flat=True,
            )
        )
    }

    for requisicao in RequisicaoLente.objects.exclude(dt_contatado=None):
        ControleLente.objects.update_or_create(
            nr_requisicao=requisicao.nr_requisicao,
            defaults={
                "paciente_contatado": True,
                "dt_contato": requisicao.dt_contatado,
                "usuario_contato": users_by_id.get(requisicao.usuario_contatou_id, ""),
                "cache_paciente": requisicao.cache_paciente,
                "cache_telefone": requisicao.cache_telefone,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('lentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleLente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_requisicao', models.CharField(max_length=50, unique=True, verbose_name='numero da requisicao')),
                ('paciente_contatado', models.BooleanField(default=False)),
                ('dt_contato', models.DateTimeField(blank=True, null=True)),
                ('usuario_contato', models.CharField(blank=True, max_length=100)),
                ('retirada_paciente', models.BooleanField(default=False)),
                ('dt_retirada', models.DateTimeField(blank=True, null=True)),
                ('usuario_retirada', models.CharField(blank=True, max_length=100)),
                ('observacao', models.TextField(blank=True)),
                ('cache_paciente', models.CharField(blank=True, max_length=255)),
                ('cache_telefone', models.CharField(blank=True, max_length=50)),
                ('cache_dt_solicitacao', models.DateTimeField(blank=True, null=True)),
                ('cache_dt_chegada_lente', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'controle operacional de lente',
                'verbose_name_plural': 'controles operacionais de lentes',
                'ordering': ['-dt_retirada', '-dt_contato', 'cache_paciente'],
            },
        ),
        migrations.AlterField(
            model_name='movimentorequisicaolente',
            name='tipo',
            field=models.CharField(choices=[('CONTATO_PACIENTE', 'Paciente contatado'), ('RETIRADA_PACIENTE', 'Retirada pelo paciente')], max_length=40),
        ),
        migrations.RunPython(migrate_existing_contacts, migrations.RunPython.noop),
    ]
